# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a3508ebf8f05e5b899b0ba2ac81a57c279827172370a7fb598c46c5f201304a7b673b7b5c58f84720df9a9b52c5bc6164d3c976eef0f9cf412511c39c2c04e77

test:
  secret_key_base: 15ff130c0dde0fd5ae728c5ceef7d88d0148779d279bc9e9555e683ee8eb73400c397e29dd2d1c0b6b95b031c996164c5367cc5c1e447c8b15c3d9eb098f5070

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
